### ISSUE TITLE
mitogen doesn't work with htpasswd module in ansible 2.9

### ISSUE THREAD

**Issue by pschiffe** [dw/mitogen#684]
When trying to use the following module with mitogen:
```
- name: create htpasswd file for basic nginx auth
  htpasswd:
    path: /home/admin/conf/web/basic-auth
    name: system
    password: secret
    state: present
```

I get:
```
Traceback (most recent call last):
  File "master:/usr/lib/python3.7/site-packages/ansible_mitogen/runner.py", line 971, in _run
    self._run_code(code, mod)
  File "master:/usr/lib/python3.7/site-packages/ansible_mitogen/runner.py", line 937, in _run_code
    exec('exec code in vars(mod)')
  File "<string>", line 1, in <module>
  File "master:/usr/lib/python3.7/site-packages/ansible/modules/web_infrastructure/htpasswd.py", line 105, in <module>
  File "/usr/lib/python2.7/site-packages/passlib/apache.py", line 475, in <module>
    htpasswd_defaults = _init_default_schemes()
  File "/usr/lib/python2.7/site-packages/passlib/apache.py", line 446, in _init_default_schemes
    bcrypt = "bcrypt" if registry.has_backend("bcrypt") else None
  File "/usr/lib/python2.7/site-packages/passlib/registry.py", line 481, in has_backend
    hasher.get_backend()
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 2055, in get_backend
    cls.set_backend()
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 2130, in set_backend
    return cls.set_backend(name, dryrun=dryrun)
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 2155, in set_backend
    cls._set_backend(name, dryrun)
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 2278, in _set_backend
    super(SubclassBackendMixin, cls)._set_backend(name, dryrun)
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 2191, in _set_backend
    ok = loader(**kwds)
  File "/usr/lib/python2.7/site-packages/passlib/handlers/bcrypt.py", line 565, in _load_backend_mixin
    return mixin_cls._finalize_backend_mixin(name, dryrun)
  File "/usr/lib/python2.7/site-packages/passlib/handlers/bcrypt.py", line 374, in _finalize_backend_mixin
    result = safe_verify("test", test_hash_20)
  File "/usr/lib/python2.7/site-packages/passlib/handlers/bcrypt.py", line 293, in safe_verify
    return verify(secret, hash)
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 761, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/usr/lib/python2.7/site-packages/passlib/handlers/bcrypt.py", line 594, in _calc_checksum
    hash = _bcrypt.hashpw(secret, config)
AttributeError: 'module' object has no attribute 'hashpw'
```

The playbook works without mitogen and I think it worked before with mitogen and ansible 2.8.

Host is Fedora 31:
```
$ ansible --version
ansible 2.9.2
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 22:52:49) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

$ rpm -q python3-mitogen
python3-mitogen-0.2.9-1.fc31.noarch
```

Destination is a fully patched CentOS 7.7. Complete ansible log from the task: [ansible_log.txt](https://github.com/dw/mitogen/files/4100768/ansible_log.txt)

**Comment by micah** [comment]
Does mitogen work with ansible 2.9? I see on the website that only 2.8 is supported
