### ISSUE TITLE
ansible 2.10 support

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#731]
There doesn't seem to be an existing issue referencing ansible 2.10 issues yet, so here goes :)

```
ansible 2.10.0b1.post0
  config file = /export/home/orion-admin/ansible-boulder/ansible.cfg
  configured module search path = [u'/export/home/orion-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /export/home/orion-admin/ansible/lib/ansible
  executable location = /export/home/orion-admin/ansible/bin/ansible
  python version = 2.7.5 (default, Apr  1 2020, 10:09:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /export/home/orion-admin/ansible-boulder/ansible.cfg as config file
Parsed /export/home/orion-admin/ansible-boulder/inventory/boulder.cobbler.yml inventory source with cobbler plugin
Skipping due to inventory source not ending in "cobbler.yaml" nor "cobbler.yml"
cobbler declined parsing /export/home/orion-admin/ansible-boulder/inventory/hosts as it did not pass its verify_file() method
Parsed /export/home/orion-admin/ansible-boulder/inventory/hosts inventory source with ini plugin
Parsed /export/home/orion-admin/ansible-boulder/inventory/monterey.cobbler.yml inventory source with cobbler plugin
Parsed /export/home/orion-admin/ansible-boulder/inventory/seattle.cobbler.yml inventory source with cobbler plugin
[top  4317] 10:19:00.884328 D ansible_mitogen.affinity: CPU mask for Ansible top-level process: 0x000002
[top  4317] 10:19:00.884631 D ansible_mitogen.process: inherited open file limits: soft=1024 hard=4096
[top  4317] 10:19:00.884730 D ansible_mitogen.process: raised soft open file limit from 1024 to 4096
[mux  4327] 10:19:00.887142 D ansible_mitogen.affinity: CPU mask for MuxProcess 0: 0x000001
[mux  4327] 10:19:00.902435 D mitogen.service: Pool(a110, size=32, th='MainThread'): initialized
[mux  4327] 10:19:00.902749 D ansible_mitogen.process: Service pool configured: size=32
META: ran handlers
[task 4361] 10:19:00.934268 D ansible_mitogen.affinity: CPU mask for WorkerProcess: 0x000004
The full traceback is:
Traceback (most recent call last):
  File "/export/home/orion-admin/ansible/lib/ansible/executor/task_executor.py", line 155, in run
    res = self._execute()
  File "/export/home/orion-admin/ansible/lib/ansible/executor/task_executor.py", line 610, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/export/home/orion-admin/ansible/lib/ansible/executor/task_executor.py", line 1063, in _get_action_handler
    collection_list=collections
  File "/export/home/orion-admin/ansible-boulder/mitogen/ansible_mitogen/strategy.py", line 144, in wrap_action_loader__get
    return adorned_klass(*args, **kwargs)
  File "/export/home/orion-admin/ansible-boulder/mitogen/ansible_mitogen/mixins.py", line 118, in __init__
    super(ActionModuleMixin, self).__init__(task, connection, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'collection_list'
barry.cora.nwra.com | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
[mux  4327] 10:19:00.980813 D mitogen: Waker(fd=6/8): disconnecting
```

**Comment by s1113950** [comment]
Thanks for the ticket! :)

I was sorta doing this in this PR here: https://github.com/dw/mitogen/pull/715  (the error you reported I started to fix in that branch),
until I got distracted by sudden failing tests here: https://github.com/dw/mitogen/pull/723

I like a dedicated ticket for 2.10 support though since there will probably be other things other than collections that need to change for 2.10.

**Comment by s1113950** [comment]
Ran into the first issue:
https://github.com/dw/mitogen/pull/715/commits/1bd4b8afcdcff636bed8f6a703769b0ad86ba791

**Comment by s1113950** [comment]
@opoplawski please give https://github.com/dw/mitogen/pull/715 a try and let me know if it fixes your issue 😄 It should work with ansible 2.10 installed from github via `pip install git+https://github.com/ansible/ansible.git@v2.10.0` since `ansible==2.10` isn't out yet.

**Comment by vincentbernat** [comment]
❦  2 septembre 2020 19:05 -07, Steven Robertson:

> @opoplawski please give https://github.com/dw/mitogen/pull/715 a try
> and let me know if it fixes your issue 😄 It should work with ansible
> 2.10 installed from github via `pip install
> git+https://github.com/ansible/ansible.git@v2.10.0` since
> `ansible==2.10` isn't out yet.

or `pip install ansible-core==2.10.0` (which should be exactly the same
as the tag).

**Comment by s1113950** [comment]
I tried it, and `ansible-core` doesn't exist 🤔 https://pypi.org/project/ansible-base/ does, but that won't come with collections. Eventually `ansible==2.10` will release with some collections inside it, see https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible.in

**Comment by vincentbernat** [comment]
❦  3 septembre 2020 21:25 -07, Steven Robertson:

> I tried it, and `ansible-core` doesn't exist 🤔
> https://pypi.org/project/ansible-base/ does, but that won't come with
> collections. Eventually `ansible==2.10` will release with some
> collections inside it, see
> https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible.in

Oh, yes, sorry! It was ansible-base.

**Comment by sbaygithub** [comment]
How is the status for the the 2.10 version? Is there any ETA for a new release?

**Comment by goldyfruit** [comment]
> How is the status for the the 2.10 support? Is there any ETA for a new release?

Same question here.

**Comment by DaVince** [comment]
I'd suggest subscribing to the pull request linked above to keep updated. 😃

**Comment by jn-itiviti** [comment]
> How is the status for the the 2.10 support? Is there any ETA for a new release?

Hello! what's the status for the 2.10+ support? I see mitogen is still under active development but no news on this front :( 
Thanks in advance 🙏

**Comment by DaVince** [comment]
> > How is the status for the the 2.10 support? Is there any ETA for a new release?
> 
> Hello! what's the status for the 2.10+ support? I see mitogen is still under active development but no news on this front :( Thanks in advance 🙏

" closed this as completed" means it's been implemented and I can confirm this. I think a better question to ask at this point is support for newer versions than that, since Red Hat has been quite busy reworking a lot of things in Ansible.
